---
- hosts: all
  become: yes
  tasks: 
  - name: installing tomcat
  apt: 
   name: apache2
   state: present
  when: ansible_os_family == "Debian"
   
- name: starting apache2 service
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian""